myapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
from django.conf import settings
from django.conf.urls.static import static
from .views import VideoCreateView,VideoUpdateView,VideoDeleteView,CommentUpdateView,CommentDeleteView


urlpatterns = [
    path('',auth_views.LoginView.as_view(),name='login'),
    path('register/',views.register,name='register'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('profile/password-reset/',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),name='password_reset'),
    path('profile/password-resset/done/',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    path('profile/password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
    path('profile/password-resset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
    path('home/',views.home,name='home'),
    path('s/',views.search,name='search'),
    path('home/category/<int:pk>/',views.category_page,name='category_page'),
    path('home/video/<int:pk>/',views.vdodetail,name='vdodetail'),
    path('home/video/<int:pk>/#',views.vlikes,name='vlikes'),
    path('home/video/<int:pk>/update/',VideoUpdateView.as_view(),name='vdoupdate'),
    path('home/video/<int:pk>/cupdate/',CommentUpdateView.as_view(),name='cupdate'),
    path('home/video/<int:pk>/delete/',VideoDeleteView.as_view(),name='vdodelete'),
    path('home/video/<int:pk>/cdelete/',CommentDeleteView.as_view(),name='cdelete'),
    path('home/video/post/',VideoCreateView.as_view(),name='vdocreate'),
    # path('profile/',views.profile,name='profile'),
    path('userprofile/<int:pk>/',views.profile_user,name='profile_user'),
    path('update/<int:pk>/',views.update,name='update'),
    path('watchlist/',views.watchlist,name='watchlist'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

vdotube/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.title

class Video(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    path = models.FileField(upload_to='video')
    added_date = models.DateTimeField(default=timezone.now)
    cat = models.ForeignKey(Category,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    like = models.ManyToManyField(User,blank=True,related_name='vlikes')

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ('cat_id',)

    def get_absolute_url(self):
        return reverse('vdodetail', kwargs={'pk': self.pk})
    
class Comment(models.Model):
    text = models.TextField()
    img = models.ImageField(upload_to='comment', blank=True)
    added_date = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    video = models.ForeignKey(Video,on_delete=models.CASCADE)
    parent = models.ForeignKey('self',on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    like = models.ManyToManyField(User,blank=True,related_name='clikes')

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('-added_date',)
    
    def get_absolute_url(self):
        return reverse('vdodetail', kwargs={'pk': self.pk})
    
    @property
    def is_reply(self):
        if self.reply is not None:
            return False
        return True


class Profile(models.Model):
    A =( 
    ("Male", "Male"), 
    ("Female", "Female"), 
    ("Others", "Others"), 
)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, blank=False)
    middle_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=False)
    Profile_Pic = models.ImageField(default='default.jpg',upload_to='profile_pic')
    Cover_pic = models.ImageField(default='default1.jpg',upload_to='cover_pic')
    Gender = models.CharField(max_length=200, blank=False, choices=A)
    date_added = models.DateField(default=timezone.now,blank=False)
    BIO = models.CharField(max_length=500)
    Contact_Number = PhoneNumberField(blank=False)
    Country = models.CharField(max_length=200, blank=False)
    Address = models.CharField(max_length=200, blank=False)

    def __str__(self):
        return f'{self.user.username} Profile'

class Wishlist(models.Model):
    video_id = models.ForeignKey(Video,on_delete=models.CASCADE)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)

templates/comment.html
<!-- {% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>VideoTube</title>
    <style>
        body{
            background-color: rgb(165, 207, 165);
            margin: 25px;
          }
          h3{
              margin: 10px;
              text-align: center;
              color: rgb(70, 0, 247);
          }
          .container{
              background-color: rgb(247, 206, 130);
              border: 2px solid black;
              padding: 35px;
          }
    label{
        width: 100%;
        font-size: 20px;
        font-weight: 500;
        margin-bottom: 0px;
    }
    input{
        width:100%;
        border: 2px solid black;
        box-sizing: 30px;
        margin-top: 7px;
        margin-bottom: 7px;
    }
    button{
        margin-top: 15px;
        background-color: rgb(2, 150, 248);
        padding: 7px;
    }
    .row{
      background-color: wheat;
      margin-top: 10px;
      margin-left: 40px;
      width: 93%;
    }
    </style>
  </head>
  <body>
    {% for message in messages %}
    <h1>{{message}}</h1>
    {% endfor %}

              <h3>Comment Here</h3>
                <div class="container">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                <label>Comment<br></label>
                <input type="text" name = "text" placeholder="Enter you Comment"><br>
                <label>Comment with Image<br></label>
                <input type="file" name = "img" placeholder="Comment Photo" accept="image/*"><br>
                {% for v in vdos %}
                <input type="hidden" name = "video" value="{{v.pk}}">
                <button type="submit" value="submit">Comment</button>
                </form>
                </div>
                <div class="row">
                  {% endfor %}
                  {% for c in coment %}
                  <div class="row">
                    <div class="col-md-1"><a href="/userprofile/{{c.user.pk}}"><img src="{{ c.user.profile.Pic.url }}" width="50" height="50" alt="" class="rounded-circle"></a></div>
                <div class="col-md-11"><div><p><b>{{c.user.username}}</b> at {{c.added_date}}</p></div><p>{{ c.text }} <img src="/media/{{c.img}}" width="80" height="80" alt=""></div>
              </div>
                  {% endfor %}
                </div>
                
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
      window.onscroll = function() {myFunction()};
      
      var nav = document.getElementById("nav");
      var sticky = nav.offsetTop;
      
      function myFunction() {
        if (window.pageYOffset >= sticky) {
          nav.classList.add("sticky")
        } else {
          nav.classList.remove("sticky");
        }
      }
      </script>
  </body>
</html> -->

templates/commentdelete.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>VideoTube</title>
    <style>
        .bg{
            background:#11cfbf!important;
        }
        a{
            font-size: 20px;
            color: rgb(255, 0, 0);
            margin: 10px;
            font-family: Comic Sans MS ;
            font-weight: 900;
            text-decoration: none;
        }
        .active{
            font-size: 35px;
            color: rgb(0, 0, 0);
            margin: 10px;
            font-family: Comic Sans MS ;
            font-weight: 900;
        }
        .form-inline input[type=search] {
            width: 250px;
            border: 2px solid green;
            font-size: 17px;
        }
        .nav{
            float: right;
            margin-left: 1px;
        }
        .media{
            margin: 12px;

        }
        h4{
            margin-top: 20px;
            margin-left: 20px;
            font-family: Courier;
        }
        label{
            color: black;
            font-size: 20px;
            margin: 0px;
            margin-left: 183px;
            color:rgb(25, 0, 253)
        }
        input{
            color: black;
            font-size: 18px;
            border: 2px solid black;
            border-radius: 12px;
            margin: 0px;
            margin-left: 183px;
            max-width: 420px;
            box-sizing: 30px;
            border: 2px solid black;
        }
        input[type=text]{
            border: 2px solid black;
            border-radius: 12px;
        }
        input[type=email]{
            border: 2px solid black;
            border-radius: 12px;
        }
        input[type=tel]{
            border: 2px solid black;
            border-radius: 12px;
        }
        .select.form-control{
            border: 2px solid black;
            border-radius: 12px;   
        }
        #hint_id_username{
            margin-left: 200px;
            color:rgb(4, 4, 255);
        }
        button{
            margin-left: 320px;
            margin-bottom: 9px;
            margin-top: 0px;
            padding: 7px;
            font-size: 20px;
            background-color: mediumseagreen;
            border-radius: 12px;
        }
        select{
            margin-left: 187px;
            max-width: 250px;
            border: 2px solid black;
            border-radius: 12px;
        }
        .content.side{
            width: 40%;
        }
        #id_description{
            margin-left: 180px;
            width: 400px;
            border: 2px solid black;
            border-radius: 12px;
        }
        h1{
            background-color: black;
            color: blanchedalmond;
            text-align: center;
        }
        .box button{
            display: center;
            margin: auto;
            margin-top: 30px;
            margin-left: 30px;
            border: 2px solid rgb(146, 126, 126);
        }
        footer{
            position: absolute;
            bottom: 0;
            clear: both;
            padding: 20px;
            text-align: center;
            background: yellow;
            color:blue;
            width: 100%;
        }
        h6{
            display: block;
            margin: initial;
            font-size: 50px;
            text-align: center;
            color:red;
            background-color: black;
        }
    </style>
  </head>
  <body>
    {% include "pnav.html" %}

    <h1>Delete Your Video</h1><br>
    <div class="box">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h4>Are you sure you want to delete the Comment ?</h4>
            <button class="btn btn-outline-danger" type="submit" value="submit">Yes, Delete</button>
            <button class="btn btn-outline-info" href="/home/video/{{object.id}}">Cancel</button>
        </form>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/main.html
<style>
    .navbar {
        overflow: visible;
        position: fixed;
        top: 0;
        width: 100%;
        z-index: 1;
    }
    
    .navbar .dropdown-menu {
        z-index: 1;
    }
</style>
<nav class="navbar navbar-expand-lg bg navbar-light">
    <img src="../media/logo.jpg" width="37" height="37" alt="">
    <a href="/home/">
        <div class="active animated infinite heartBeat delay-3s">VideoTube</div>
    </a>
    <li class="nav-link">
        <a href="#">Contact</a>
    </li>
    <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categories
      </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
                {% for c in cats %}
                <a class="dropdown-item" href="/home/category/{{c.pk}}">{{c.title}}</a> {% endfor %}
            </li>
        </div>
    </div>
    <form class="form-inline my-2 my-lg-0" method="GET" action="/s/">
        <input class="form-control mr-sm-2" name="keywords" type="search" value="{{ request.GET.keywords }}" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Search</button>
    </form>
    <ul class="nav">
        <li class="greeting">
            <a class="nav-link disabled" href="#">
                <script>
                    var now = new Date();
                    var hrs = now.getHours();
                    var ap = "AM";
                    var msg = "";

                    if (hrs > 5) msg = "Good Morning";
                    if (hrs > 11) msg = "Good Afternoon";
                    if (hrs > 16) msg = "Good Evening";
                    if (hrs > 19) msg = "Good Night";

                    document.write(msg);
                </script> {{user.username}}</a>
        </li>
    </ul>
    <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="rounded-circle account-img" src="{{ user.profile.Profile_Pic.url }}" width="55" height="50" alt="">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="/watchlist">Watch Later</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/userprofile/{{user.pk}}">Profile</a>
            </li>
            <li>
                <a class="nav-link" href="/update/{{user.pk}}">Profile Update</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/logout/">Logout</a>
            </li>
            {% endif %}
        </div>
    </div>
    </div>
</nav>

templates/pnav.html
<div class="navbar navbar-expand-lg bg navbar-light ">
    <!-- <img src="../media/logo.jpg" width="37" height="37" alt="">class="active animated infinite heartBeat delay-3s" -->
  <a class="active" href="/home/"><div >VideoTube</div></a>
  <li class="nav-link">
    <a href="#">Contact</a>
  </li>
    <ul class="nav">
        {% if user.is_authenticated %}
        
        <li>
            <a class="nav-link disabled" href="#"> <script>
                var now = new Date();
          var hrs = now.getHours();
          var ap = "AM";
          var msg = "";
          
          if (hrs >  5) msg = "Good Morning";
          if (hrs >  11) msg = "Good Afternoon";
          if (hrs > 16) msg = "Good Evening";      
          if (hrs > 19) msg = "Good Night";        
          
          document.write(msg);
          
              </script> {{user.username}}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/userprofile/{{user.pk}}">Profile</a>
        </li>
        <li>
            <a class="nav-link" href="/update/{{user.pk}}">Profile Update</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/logout/">Logout</a>
        </li>
        {% endif %}
      </ul>
</div>
</div>

templates/vdodelete.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>VideoTube</title>
    <style>
        .bg{
            background:#11cfbf!important;
        }
        a{
            font-size: 20px;
            color: rgb(255, 0, 0);
            margin: 10px;
            font-family: Comic Sans MS ;
            font-weight: 900;
            text-decoration: none;
        }
        .active{
            font-size: 35px;
            color: rgb(0, 0, 0);
            margin: 10px;
            font-family: Comic Sans MS ;
            font-weight: 900;
        }
        .form-inline input[type=search] {
            width: 250px;
            border: 2px solid green;
            font-size: 17px;
        }
        .nav{
            float: right;
            margin-left: 1px;
        }
        .media{
            margin: 12px;

        }
        h4{
            margin-top: 20px;
            margin-left: 20px;
            font-family: Courier;
        }
        label{
            color: black;
            font-size: 20px;
            margin: 0px;
            margin-left: 183px;
            color:rgb(25, 0, 253)
        }
        input{
            color: black;
            font-size: 18px;
            border: 2px solid black;
            border-radius: 12px;
            margin: 0px;
            margin-left: 183px;
            max-width: 420px;
            box-sizing: 30px;
            border: 2px solid black;
        }
        input[type=text]{
            border: 2px solid black;
            border-radius: 12px;
        }
        input[type=email]{
            border: 2px solid black;
            border-radius: 12px;
        }
        input[type=tel]{
            border: 2px solid black;
            border-radius: 12px;
        }
        .select.form-control{
            border: 2px solid black;
            border-radius: 12px;   
        }
        #hint_id_username{
            margin-left: 200px;
            color:rgb(4, 4, 255);
        }
        button{
            margin-left: 320px;
            margin-bottom: 9px;
            margin-top: 0px;
            padding: 7px;
            font-size: 20px;
            background-color: mediumseagreen;
            border-radius: 12px;
        }
        select{
            margin-left: 187px;
            max-width: 250px;
            border: 2px solid black;
            border-radius: 12px;
        }
        .content.side{
            width: 40%;
        }
        #id_description{
            margin-left: 180px;
            width: 400px;
            border: 2px solid black;
            border-radius: 12px;
        }
        h1{
            background-color: black;
            color: blanchedalmond;
            text-align: center;
        }

        .box button{
            display: center;
            margin: auto;
            margin-top: 30px;
            margin-left: 30px;
            border: 2px solid rgb(146, 126, 126);
        }
        footer{
            position: absolute;
            bottom: 0;
            clear: both;
            padding: 20px;
            text-align: center;
            background: yellow;
            color:blue;
            width: 100%;
        }
        h6{
            display: block;
            margin: initial;
            font-size: 50px;
            text-align: center;
            color:red;
            background-color: black;
        }
    </style>
  </head>
  <body>
    {% include "pnav.html" %}

    <h1>Delete Your Video</h1><br>
    <div class="box">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h4>Are you sure you want to delete the post "{{ object.title }}" ?</h4>
            <button class="btn btn-outline-danger" type="submit" value="submit">Yes, Delete</button>
            <button class="btn btn-outline-info" href="/home/video/{{object.id}}">Cancel</button>
        </form>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/vdoform.html
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>VideoTube</title>
    <style>
        .bg{
            background:#11cfbf!important;
        }
        a{
            font-size: 20px;
            color: rgb(255, 0, 0);
            margin: 10px;
            font-family: Comic Sans MS ;
            font-weight: 900;
            text-decoration: none;
        }
        .active{
            font-size: 35px;
            color: rgb(0, 0, 0);
            margin: 10px;
            font-family: Comic Sans MS ;
            font-weight: 900;
        }
        .form-inline input[type=search] {
            width: 250px;
            border: 2px solid green;
            font-size: 17px;
        }
        .nav{
            float: right;
            margin-left: 1px;
        }
        .media{
            margin: 12px;

        }
        h4{
            margin-top: 20px;
            margin-left: 20px;
            font-family: Courier;
        }
        label{
            color: black;
            font-size: 20px;
            margin: 0px;
            margin-left: 183px;
            color:rgb(25, 0, 253)
        }
        input{
            color: black;
            font-size: 18px;
            border: 2px solid black;
            border-radius: 12px;
            margin: 0px;
            margin-left: 183px;
            max-width: 420px;
            box-sizing: 30px;
            border: 2px solid black;
        }
        input[type=text]{
            border: 2px solid black;
            border-radius: 12px;
        }
        input[type=email]{
            border: 2px solid black;
            border-radius: 12px;
        }
        input[type=tel]{
            border: 2px solid black;
            border-radius: 12px;
        }
        .select.form-control{
            border: 2px solid black;
            border-radius: 12px;   
        }
        #hint_id_username{
            margin-left: 200px;
            color:rgb(4, 4, 255);
        }
        button{
            width: 80px;
            margin-left: 320px;
            margin-bottom: 20px;
            padding: 7px;
            font-size: 20px;
            background-color: mediumseagreen;
            border-radius: 12px;
        }
        select{
            margin-left: 187px;
            max-width: 250px;
            border: 2px solid black;
            border-radius: 12px;
        }
        .content.side{
            width: 40%;
        }
        #id_description{
            margin-left: 180px;
            width: 400px;
            border: 2px solid black;
            border-radius: 12px;
        }
        h1{
            background-color: black;
            color: blanchedalmond;
            text-align: center;
        }
        footer{
            position: absolute;
            bottom: 0;
            clear: both;
            padding: 20px;
            text-align: center;
            background: yellow;
            color:blue;
            width: 100%;
        }
        h6{
            display: block;
            margin: initial;
            font-size: 50px;
            text-align: center;
            color:red;
            background-color: black;
        }
    </style>
  </head>
  <body>
    {% include "pnav.html" %}

    <h1>Post Your Video</h1><br>
    <div class="box">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" value="submit">Post</button>
        </form>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>